#插件版本
#Plugin Version
Version: '3.6.0'

#语言设置,中文为zh_cn,英文为en_us
#Language setting, Chinese is zh_cn, English is en_us
Lunguage: 'zh_cn'

#是否启用自动检查更新
#Enable automatic check for updates
Update: true

#以下为各个作弊检测的设置
#The following is the setting of each cheating detection
Chect:
  Speed: #Speed
    active: true #是否启用检测 Enable detection
    actions: 'kick' #kick是踢出,ban是封禁,cancel是仅拉回 Kick means kick, ban means ban, cancel means cancel
    VLMax: 2 #触发几次后进行处罚 Penalty will be given after triggering several times
    delay: 70 #每一次检测的延迟(ms) Delay of each detection (MS)
    weight: 0.03 #有多少偏移值算触发 How many offset values are triggered
  #虽然Fly检测的代码我写了，但是存在BUG，因此暂时只有Speed检测
  #Although I wrote the code for fly detection, there are many bugs, so only speed detection is available for the time being
  Fly: #Speed
    active: false #是否启用检测 Enable detection
    actions: 'kick' #kick是踢出,ban是封禁 Kick means kick, ban means ban, cancel means cancel
    VLMax: 13 #触发几次后进行处罚 Penalty will be given after triggering several times
    delay: 60 #每一次检测的延迟(ms) Delay of each detection (MS)
    weight: 0.0005 #有多少偏移值算触发 How many offset values are triggered
